### PR TITLE
add template dir to use it from outside

### PR DESCRIPTION
**Pull request by DrMabuse23**
#### Short description of what this resolves:
setting the template dir to generate a page from outside

#### Changes proposed in this pull request:

- setting templateDir 

**Fixes**: #1180

### CODE REVIEW

**Comment by janpio** [comment]
What exactly does this do?
Why is it useful?
Why is this needed?

**Comment by DrMabuse23** [comment]
did you read the [issue #1180 ](https://github.com/ionic-team/ionic-app-scripts/issues/1180) ?

**Comment by janpio** [comment]
I actually missed that link. Sorry.

But: I still don't really understand. What does setting the template dir allow me to do?

**Comment by DrMabuse23** [comment]
its allow me to set the templateDir you have to checkout the code i have to use it from outside the ionic Project to generate some files so  i cant ovverride the static const 
````
 const page = hydrateRequest(context, request, templateDir);
    return Observable.fromPromise(generateTemplates(context, page, true))
      .map((res) => [page, res]);
````
like this

**Comment by DrMabuse23** [comment]
Thanks for your wonderful Support  => NOT

**Pull request closed without merging**
