### PR TITLE
Improve perf of lint

### PR DESCRIPTION
**Pull request by rolandjitsu**
#### Short description of what this resolves:
Address the performance of linting. It currently takes around `24s` to lint the conference app, but with the latest changes it takes on average `2s`.

#### Changes proposed in this pull request:

- create a TS program and linter only once per linting instance
- fetch lint results only after all files have been linted
- fix lint errors for src
- fix npm warning (complains about missing peer dep. `@angular/animations`)
- bump tslint-eslint-rules to latest (which uses TSLint v5)

**Fixes**: #

@danbucholtz thanks for pointing out the slowness 👍

### CODE REVIEW

**Comment by danbucholtz** [comment]
Will merge next week. Thanks!!

**Comment by danielsogl** [comment]
@rolandjitsu Fix the conflicts so we can test the changes.

**Comment by rolandjitsu** [comment]
@danielsogl done 😄

**Comment by danbucholtz** [comment]
Thanks @rolandjitsu 🎉 

Thanks,
Dan

**Comment by adamgalmor** [comment]
Hi all
Thank you for your hard work!
How can I be informed of this fix release?

**Comment by danbucholtz** [comment]
@adamgalmor, it's not published yet. I need to do some testing.

Thanks,
Dan

**Pull request merged**
