### PR TITLE
Fix Babili Minification

### PR DESCRIPTION
**Pull request by jwelmac**
#### Short description of what this resolves:
Resolves minifiying code to ES6 using Babili no longer working

#### Changes proposed in this pull request:
- edit taskInfo in babili.js to resolve conflict between config file and value command line and package.json values
- Change babili package.json config to match others
- Add shortArg for babili

**Fixes**: #896

### CODE REVIEW

**Comment by mburger81** [comment]
@jwelmac Do you think this PR could also resolve this issues: #911 #877

**Comment by danbucholtz** [comment]
I gotta take a look at this PR. Thanks for submitting.

Thanks,
Dan

**Comment by jwelmac** [comment]
Hey @mburger81,
I think it may resolve those issues. Reading through the issues it does seem that they are related to using code that needs to be run as ES2015/ES6. To minify these in a production build Babili would be the choice.
If you wish to try it out before the PR is incorporated use the following steps:
1. Add the custom configuration to use Babili for minification eg. in package.json add the following:
```json
"config": {
    "ionic_use_experimental_babili": "true"
}
```
2. Run the following command in your app's top-level directory (Unix or Mac).
```
find ./node_modules/@ionic/app-scripts/dist/babili.js -type f -exec sed -i 's/IONIC_USE_EXPERIMENTAL_BABILI/IONIC_BABILI/;s/ionic_use_experimental_babili/ionic_babili/' {} \;
```
3. Run the production build command, eg. `npm run build --prod`

**Note:** If you don't wish to edit your package.json do `step 2` then at `step 3` change the command to `npm run build --prod --babili`

Let me know if this helps.

P.S. @samastur take a look and see if this helps.

**Comment by mburger81** [comment]
Hey @jwelmac thx for your great help.
This morning we tested it and it seams to bee working, at leatst the `npm run build --prod` does not throws any errors. After that we migrated to new ionic-angular 3.1.0 and also new ionic-cli v3.beta9 and from there we are on a bug where we can not go back!!!!

So for now we can not develop nor we can resolve production errors.
This is the bug where we are in!
https://github.com/driftyco/ionic-app-scripts/issues/927#issuecomment-297681308

We will let you know when we run out of the bug and can go ahead with your test!

Thx a lot

**Comment by mburger81** [comment]
@jwelmac It seems your "workaround" yesterday it does work or at least it was able to create the build, but today with version 1.3.6 It seems it doesn't work! Is tat possible?

**Comment by mburger81** [comment]
:+1: :+1: 
I can confirm the workaround is resolving my issue #877 and perhaps also @samastur #911

**Comment by jwelmac** [comment]
Hey @mburger81,
Do you mind sharing the error message you are getting now with 1.3.6?


On Apr 28, 2017 7:39 AM, wrote:

Glad it was able to help. I will do some checks with 1.3.6 and see what I
come up with.
Hope your other bugs get ironed out soon.

On Apr 28, 2017 6:01 AM, "mburger81" <notifications@github.com> wrote:

@jwelmac <https://github.com/jwelmac> It seems your "workaround" yesterday
it does work or at least it was able to create the build, but today with
version 1.3.6 It seems it doesn't work! Is tat possible?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/driftyco/ionic-app-scripts/pull/897#issuecomment-297946813>,
or mute the thread

**Comment by jwelmac** [comment]
Glad it was able to help. I will do some checks with 1.3.6 and see what I
come up with.
Hope your other bugs get ironed out soon.

**Comment by samastur** [comment]
Regretfully it doesn't fix it for me neither on 1.3.4 nor 1.3.6. I can build production version of our app, but it fails with the same run time errors as dev build described in #911.

Still, it feels like a step in the right direction.

**Comment by mburger81** [comment]
If I rename my `.js` file in `.ts` as suggested by @danbucholtz in his last post in #898 it does not work.
On ionic serve or --prod build there are many typescript error, so the JavaScript file nit compliant to a .ts file.

So this is no solutions for us.

He also suggest to use NPM to include javascript files, but this is a "lot" of work to include only one file? Do you don't think so?

@jwelmac: In the scenario Dan posted this PR in his opinion is obsolete, right?

**Comment by jwelmac** [comment]
Hey @mburger81,
Dan's scenario doesn't render this PR absolete.
This PR still addresses the situations in which you want your minified build files to be output in ES6. Hence the use of Babili.

**Comment by danbucholtz** [comment]
@jwelmac,

We have decided to deprecate babelili support in favor of uglify-es.

Thanks for contributing to Ionic and I'm sorry we couldn't get this merged for you.

Thanks,
Dan

**Comment by jwelmac** [comment]
@danbucholtz 

Hey Dan,
I totally understand. 

Ionic is growing and there will be lots more opportunity to contribute.

Take care,  
Jermaine

**Pull request closed without merging**
