### PR TITLE
Bump node-sass to 4.9.3 to fix security warnings

### PR DESCRIPTION
**Pull request by vially**
This should fix the security warnings `npm audit` reports (related to the `hoek` library).

### CODE REVIEW

**Comment by dwieeb** [comment]
Thanks @vially!

**Comment by ammarhaiderbjss** [comment]
@dwieeb Has this change been published to npm? Do you need to bump the package version too?

**Comment by dwieeb** [comment]
@ammarhaiderbjss Sorry, not yet. I was hoping to do some work on the new environments feature first.

**Comment by vially** [comment]
Instead of waiting for the new features (which might take some time to implement), could a new release be published which includes this patch (or maybe even #1493 if possible)?

Lots of people seem to be affected by this vulnerability and I think it's a good idea to get a new release out as soon as possible.

**Comment by Enrico204** [comment]
I agree with @vially : if new features are not ready yet, just release a bugfix version (as these bugfixes are actually security fixes)

**Pull request merged**
